name: deploy to raspberry

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  pull:
      runs-on: self-hosted
      steps:
        - uses: actions/checkout@v2
        - name: pull repository
          run: |
             cd "$HOME"/nala-OS-self-hosted
             git pull
        
