name: deploy to raspberry

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  pull:
      runs-on: self-hosted
      steps:
        -uses: actions/checkout@v2

        -name: deployment
        run: |
          echo Home=$Home
          cd $Home/nala-os
          git pull